---
authors:
  - Ansible (https://github.com/ansible)
description: GCP roles and playbooks for Ansible.
documentation: ''
homepage: ''
issues: https://github.com/redhat-cop/cloud.gcp_ops/issues
license_file: LICENSE
namespace: cloud
name: gcp_ops
version: 3.0.0-dev0
readme: README.md
repository: https://github.com/redhat-cop/cloud.gcp_ops
tags:
  - gcp
  - cloud
  - infrastructure
dependencies:
  google.cloud: '>=1.2.0'
  community.libvirt: '>=1.2.0'
  community.general: '>=7.4.0'
build_ignore:
  - .DS_Store
  - '*.tar.gz'
  - "*cloud-config-gcp.ini"
  - "*cloud-config-gcp.yml"
  - changelogs/.plugin-cache.yaml
