---
authors:
  - Ansible (https://github.com/ansible)
description: GCP roles and playbooks for Ansible.
documentation: ''
homepage: ''
issues: https://github.com/ansible-collections/cloud.gcp_ops/issues
license_file: LICENSE
namespace: cloud
name: gcp_ops
version: 1.0.0
readme: README.md
repository: https://github.com/ansible-collections/cloud.aws_gcp
tags:
  - gcp
  - cloud
  - infrastructure
dependencies:
  google.cloud: '>=1.2.0'
build_ignore:
  - .DS_Store
  - '*.tar.gz'
